#!/usr/bin/env bash
set -e
pushd ~/.config/nix-darwin
nvim
alejandra . &>/dev/null
git diff -U0
echo "NixOS Rebuilding..."
darwin-rebuild switch --flake ~/.config/nix-darwin &>nix-switch.log || (
 cat nix-switch.log | grep --color error && false)
gen=$(darwin-rebuild --list-generations | grep current)
git commit -am "$gen"
popd